### ISSUE TITLE
Question: ZclIasZoneClient ignores attribute value cache

### ISSUE THREAD

**Issue by triller-telekom** [zsmartsystems/com.zsmartsystems.zigbee#1022]
We recently spotted the "warning":

```
WARN:	[symbolicName=com.zsmartsystems.zigbee, className=com.zsmartsystems.zigbee.app.iasclient.ZclIasZoneClient] - C820/1: IAS CIE address is NOT confirmed null
```

which was a result of 

https://github.com/zsmartsystems/com.zsmartsystems.zigbee/blob/a53b0bcf7e87b24c68218db8b0e94493a1efcd85/com.zsmartsystems.zigbee/src/main/java/com/zsmartsystems/zigbee/app/iasclient/ZclIasZoneClient.java#L198-L209

where only "debug" was logged:

```
DEBUG:	[symbolicName=com.zsmartsystems.zigbee, className=com.zsmartsystems.zigbee.app.iasclient.ZclIasZoneClient] - C820/1: IAS CIE failed to get state
```

The question is: Is there a (maybe security related) reason why the call:

```
Integer currentState = (Integer) iasZoneCluster.getAttribute(ZclIasZoneCluster.ATTR_ZONESTATE).readValue(0);
```

uses `readValue(0)`, so it intentionally ignores the ZSS cache and tries to query the device?

In our case it was a Bitron Video 902010/21B door window contact which was probably sleeping when the `ZclIasZoneClient` was initializing.

If there isn't any specific reason, the call could use the cache and see that the client is still enrolled on the device.

**Comment by cdjackson** [comment]
I don't see any specific need to not use the cache, so I think this could be changed if you want to propose a PR Stefan?
