### ISSUE TITLE
Overlapping attribute ids

### ISSUE THREAD

**Issue by spudwebb** [zsmartsystems/com.zsmartsystems.zigbee#1035]
Some cluster attributes ids are overlapping, see for example in ZclMeteringCluster.java

```
public static final int ATTR_PREVIOUSDAY16CONSUMPTIONRECEIVED = 0x0431;

public static final int ATTR_CURRENTWEEKCONSUMPTIONRECEIVED = 0x0431;
```
I believe the issue is here:
https://github.com/zsmartsystems/com.zsmartsystems.zigbee/blob/759570d1975c25395c87c41507046e2340b608a2/com.zsmartsystems.zigbee.autocode/src/main/java/com/zsmartsystems/zigbee/autocode/ZigBeeZclClusterGenerator.java#L176-L177

I think the id shouldn't be generated as (attribute.code + arrayCount) but as (attribute.code + arrayCount - attribute.arrayStart)

**Comment by cdjackson** [comment]
Thanks. It looks like you’re probably correct - if you’re able to provide a PR for this change it would be appreciated?

**Comment by spudwebb** [comment]
sorry I can't. I found and fixed the problem in the ZigbeeNet project (https://github.com/Mr-Markus/ZigbeeNet/pull/112), and I thought I would mention it here because I checked there was the same issue here, but I don't have a java dev environment to make a PR for this project.

**Comment by cdjackson** [comment]
Ok, thanks for reporting. I'll take a look.
