### ISSUE TITLE
Transaction queue filling up

### ISSUE THREAD

**Issue by cdjackson** [zsmartsystems/com.zsmartsystems.zigbee#1054]
An openHAB user has reported that commands stop being sent to a Centralite thermostat. From the logs, initially it does work ok, but at some stage the transaction queue length is increasing, and nothing is ever sent to the device again.

**Comment by wtf911** [comment]
Just bumping this.

**Comment by cdjackson** [comment]
I think that this may have been resolved with #1110 which increases the transaction timeout and #1113 which removes transactions from the queue if they time out.

Without these two changes, transactions could time out, but remain in the queue, and the application may also re-queue them, thus resulting in the queue increasing.

I'll close this and if there's further issues we will need to look at it again.
