### ISSUE TITLE
ZigBeeNetworkDiscoverer has two discovery methods that need to be fixed

### ISSUE THREAD

**Issue by triller-telekom** [zsmartsystems/com.zsmartsystems.zigbee#1106]
I thought #1103 had fixed the bug with the discovery always using the broadcast address, however there is a SECOND method that suffers from the same bug.

https://github.com/zsmartsystems/com.zsmartsystems.zigbee/blob/master/com.zsmartsystems.zigbee/src/main/java/com/zsmartsystems/zigbee/app/discovery/ZigBeeNetworkDiscoverer.java#L268

It took me a while to find this as the methods look similar, and the difference is the `IeeeAddressRequest` vs `NetworkAddressRequest` which are created.

Also one of them does not implement the reaction on an interrupt:
```
if (Thread.currentThread().isInterrupted()) {
                        return;
                    }
```

I will provide a fix to get them back in sync, but we should certainly refactor this at some point, because code duplication is always bad...

**Comment by cdjackson** [comment]
Thanks Stefan
