### ISSUE TITLE
Usb doggle CC2531: I cannot see any method that scan device zigbee client

### ISSUE THREAD

**Issue by trunghtdev** [zsmartsystems/com.zsmartsystems.zigbee#1132]
Hi @cdjackson 

I already startuped zigbee doggle cc2531 in my web service but I have not found any method that scan zigbee device client

Please , help me!

**Comment by cdjackson** [comment]
Please study the console application. This provides all the functions you should need.

**Comment by trunghtdev** [comment]
Thks
