### ISSUE TITLE
[CC2531] networkManager.shutdown: when I shutdown network, it run forever

### ISSUE THREAD

**Issue by trunghtdev** [zsmartsystems/com.zsmartsystems.zigbee#1147]
@POST
	@Path("/quit")
	@Produces({ MediaType.APPLICATION_JSON })
	public Response quit() throws Exception {
		try {
			if (ZigBeeCC2531.zigBeeNetworkManager == null) {
				throw new IllegalStateException("Network null.");
			}
			ZigBeeCC2531.zigBeeNetworkManager.shutdown();
			return Response.status(200).entity("" + Boolean.TRUE).build();
		} catch (Exception e) {
			throw e;
		}
	}

**Comment by cdjackson** [comment]
Please actually describe the bug? I'm not sure what your issue is here?

I think I've also suggested in the past that you should use the public interface, and not the CC2531 interface. Please do.

If you still have a bug to report, then please provide information about the bug.
