### ISSUE TITLE
Z3Light - EFR32 could not join into EFR32 dongle network: Z3LightSoc down when run "Update TC Link Key"

### ISSUE THREAD

**Issue by trunghtdev** [zsmartsystems/com.zsmartsystems.zigbee#1182]
**Describe the bug**

> ZLL Commissioning Common: ZllCommStackStatus: status = 90, flags = 00
> NWK Steering stack status 0x90
> NWK Steering network joined.
> Find and Bind Target: Start target: 0x00
> Find and bind target start: 0x00
> RX: ZDO, command 0x0013, status: 0x00
> Device Announce: 0x5134
> Update TC Link Key: Starting update trust center link key process: 0x00
> RX: ZDO, command 0x8002, status: 0x00
> RX: Node Desc Resp, Matches: 0x0000
> Update TC Link Key: Error: 0x04
> Partner: 00 00 00 00 00 00 00 00 
> NWK Steering: Trust center link key update status: 0x04
> NWK Steering Stop.  Cleaning up.
> Join network complete: 0xAE
> NWK Creator: Cannot start. State: 0x00
> Form network start: 0x70
> EMBER_NETWORK_DOWN
> ZLL Commissioning Common: ZllCommStackStatus: status = 91, flags = 00
> NWK Steering stack status 0x91
> 

**When I use Z3GatewayHost, It joined successfully**

> RX: ZDO, command 0x0013, status: 0x00
> Device Announce: 0x6308
> Update TC Link Key: Starting update trust center link key process: 0x00
> RX: ZDO, command 0x8002, status: 0x00
> RX: Node Desc Resp, Matches: 0x0000
> Update TC Link Key: New key established: 0x03
> Partner: 78 F0 D8 FE FF 57 0B 00 
> NWK Steering: Trust center link key update status: 0x03
> Update TC Link Key: New key established: 0x65
> Partner: 78 F0 D8 FE FF 57 0B 00 
> NWK Steering: Trust center link key update status: 0x65
> pJoin for 180 sec: 0x00
> NWK Steering: Broadcasting permit join: 0x00
> NWK Steering Stop.  Cleaning up.
> Join network complete: 0x00

**Log when I use zsmartsystem**

> DeviceAnnounce [5134/0 -> 0000/0, cluster=0013, TID=81, nwkAddrOfInterest=5134, ieeeAddr=000B57FFFEDE9FD1, capability=8E]

> NodeDescriptorResponse [5134/0 -> 0000/0, cluster=8002, TID=07, status=SUCCESS, nwkAddrOfInterest=5134, nodeDescriptor=NodeDescriptor [apsFlags=0, bufferSize=82, complexDescriptorAvailable=false, manufacturerCode=1002, logicalType=ROUTER, serverCapabilities=[], incomingTransferSize=82, outgoingTransferSize=82, userDescriptorAvailable=false, frequencyBands=[FREQ_2400_MHZ], macCapabilities=[FULL_FUNCTION_DEVICE, MAINS_POWER, RECEIVER_ON_WHEN_IDLE], extendedEndpointListAvailable=false, extendedSimpleDescriptorListAvailable=false, stackCompliance=22]]

> PowerDescriptorResponse [5134/0 -> 0000/0, cluster=8003, TID=08, status=SUCCESS, nwkAddrOfInterest=5134, powerDescriptor=PowerDescriptor [currentPowerMode=RECEIVER_ON_IDLE, availablePowerSources=[MAINS], currentPowerSource=MAINS, powerLevel=FULL]]ActiveEndpointsResponse [5134/0 -> 0000/0, cluster=8005, TID=09, status=SUCCESS, nwkAddrOfInterest=5134, activeEpList=[1, 2, 242]]

> SimpleDescriptorResponse [5134/0 -> 0000/0, cluster=8004, TID=0A, status=SUCCESS, nwkAddrOfInterest=5134, length=20, simpleDescriptor=SimpleDescriptor [endpoint=1, profileId=0104, deviceId=0101, deviceVersion=1, inputClusterList=[0000, 0003, 0004, 0005, 0006, 0008], outputClusterList=[]]]

> SimpleDescriptorResponse [5134/0 -> 0000/0, cluster=8004, TID=0B, status=SUCCESS, nwkAddrOfInterest=5134, length=24, simpleDescriptor=SimpleDescriptor [endpoint=2, profileId=0104, deviceId=010D, deviceVersion=1, inputClusterList=[0000, 0003, 0004, 0005, 0006, 0008, 0300, 1000], outputClusterList=[]]]

> SimpleDescriptorResponse [5134/0 -> 0000/0, cluster=8004, TID=0C, status=SUCCESS, nwkAddrOfInterest=5134, length=10, simpleDescriptor=SimpleDescriptor [endpoint=242, profileId=A1E0, deviceId=0061, deviceVersion=1, inputClusterList=[], outputClusterList=[0021]]]

> NodeDescriptorRequest NodeDescriptorRequest [5134/0 -> 0000/0, cluster=0002, TID=82, nwkAddrOfInterest=0000]

**Log when I use Z3GatewayHost**

> 2020-12-10T02:47:41.059Z - info: Gateway: TC Join Callback 0E49 , decision: 0, status: 1
> 000B57FFFEDE9FD1 STANDARD_SECURITY_UNSECURED_JOIN
> 2020-12-10T02:47:41.079Z - info: Gateway: new device line 595
> 2020-12-10T02:47:41.094Z - info: Gateway: (>)000B57FFFEDE9FD1
> 2020-12-10T02:47:41.229Z - info: Gateway: 0E49:  
> Active Endpoints Response
> number of ep: 3
> ep: 1
> ep: 2
> ep: 242
> (>)000B57FFFEDE9FD1
> 2020-12-10T02:47:41.251Z - info: MQTT Received (topic): gw/000B57FFFED8F078/apsresponse
> 2020-12-10T02:47:41.251Z - info: MQTT Received (message): {"statusType":"apsAck","eui64":"0x00005500863E0005","status":"0x00","clusterId":"0x0005","commandId":"0x0E"}
> 2020-12-10T02:47:41.300Z - info: Gateway: (>)000B57FFFEDE9FD1
> 2020-12-10T02:47:41.315Z - info: Gateway: 0E49:  
> Simple Descriptor Response
> 2020-12-10T02:47:41.316Z - info: MQTT Received (topic): gw/000B57FFFED8F078/devicejoined
> 2020-12-10T02:47:41.316Z - info: MQTT Received (message): {"nodeId":"0x0E49","deviceState":16,"deviceType":"0x0101","timeSinceLastMessage":1450,"deviceEndpoint":{"eui64":"0x000B57FFFEDE9FD1","endpoint":1,"clusterInfo":[{"clusterId":"0x0000","clusterType":"In"},{"clusterId":"0x0003","clusterType":"In"},{"clusterId":"0x0004","clusterType":"In"},{"clusterId":"0x0005","clusterType":"In"},{"clusterId":"0x0006","clusterType":"In"},{"clusterId":"0x0008","clusterType":"In"}]}}
> 2020-12-10T02:47:41.318Z - info: MQTT Received (topic): gw/000B57FFFED8F078/apsresponse
> 2020-12-10T02:47:41.318Z - info: MQTT Received (message): {"statusType":"apsAck","eui64":"0x000B57FFFEDE9FD1","status":"0x00","clusterId":"0x0004","commandId":"0x0E"}
> 2020-12-10T02:47:41.319Z - info: MQTT Published Topic: publishstate
> 2020-12-10T02:47:41.319Z - info: Gateway: Handling Publish State Message
> Handling Commands Message: {"commands":[{"command":"plugin network-creator-security open-network","postDelayMs":100}]}
> 2020-12-10T02:47:41.362Z - info: MQTT Published Topic: commands Payload: {"commands":[{"command":"plugin network-creator-security open-network","postDelayMs":100}]}
> 2020-12-10T02:47:41.362Z - info: MQTT Received (topic): gw/000B57FFFED8F078/publishstate
> 2020-12-10T02:47:41.362Z - info: MQTT Received (message): {}
> 2020-12-10T02:47:41.362Z - info: MQTT Received (topic): gw/000B57FFFED8F078/commands
> 2020-12-10T02:47:41.362Z - info: MQTT Received (message): {"commands":[{"command":"plugin network-creator-security open-network","postDelayMs":100}]}
> 2020-12-10T02:47:41.364Z - info: Gateway: (>)000B57FFFEDE9FD1
> 2020-12-10T02:47:41.364Z - info: MQTT Received (topic): gw/000B57FFFED8F078/settings
> 2020-12-10T02:47:41.364Z - info: MQTT Received (message): {"ncpStackVersion":"6.2.3-204","networkUp":true,"networkPanId":"0x2000","radioTxPower":30,"radioChannel":11}
> 2020-12-10T02:47:41.365Z - info: MQTT Received (topic): gw/000B57FFFED8F078/relays
> 2020-12-10T02:47:41.365Z - info: MQTT Received (message): {"relays":[]}
> 2020-12-10T02:47:41.365Z - info: MQTT Received (topic): gw/000B57FFFED8F078/devices
> 2020-12-10T02:47:41.365Z - info: MQTT Received (message): {"devices":[{"nodeId":"0x0E49","deviceState":16,"deviceType":"0x0101","timeSinceLastMessage":1450,"deviceEndpoint":{"eui64":"0x000B57FFFEDE9FD1","endpoint":1,"clusterInfo":[{"clusterId":"0x0000","clusterType":"In"},{"clusterId":"0x0003","clusterType":"In"},{"clusterId":"0x0004","clusterType":"In"},{"clusterId":"0x0005","clusterType":"In"},{"clusterId":"0x0006","clusterType":"In"},{"clusterId":"0x0008","clusterType":"In"}]}}]}
> 2020-12-10T02:47:41.404Z - info: Gateway: gateway command executed: plugin network-creator-security open-network
> 2020-12-10T02:47:41.404Z - info: MQTT Received (topic): gw/000B57FFFED8F078/executed
> 2020-12-10T02:47:41.405Z - info: MQTT Received (message): {"command":"plugin network-creator-security open-network"}
> 2020-12-10T02:47:41.414Z - info: Gateway: Ezsp Policy: set Trust Center Policy to "Allow preconfigured key joins":Success: set
> 2020-12-10T02:47:41.429Z - info: Gateway: pJoin for 180 sec: 0x00
> 2020-12-10T02:47:41.444Z - info: Gateway: NWK Creator Security: Open network: 0x00
> 0E49:  
> Simple Descriptor Response
> 2020-12-10T02:47:41.445Z - info: MQTT Received (topic): gw/000B57FFFED8F078/devicejoined
> 2020-12-10T02:47:41.445Z - info: MQTT Received (message): {"nodeId":"0x0E49","deviceState":16,"deviceType":"0x0101","timeSinceLastMessage":1450,"deviceEndpoint":{"eui64":"0x000B57FFFEDE9FD1","endpoint":1,"clusterInfo":[{"clusterId":"0x0000","clusterType":"In"},{"clusterId":"0x0003","clusterType":"In"},{"clusterId":"0x0004","clusterType":"In"},{"clusterId":"0x0005","clusterType":"In"},{"clusterId":"0x0006","clusterType":"In"},{"clusterId":"0x0008","clusterType":"In"}]}}
> 2020-12-10T02:47:41.445Z - info: MQTT Received (topic): gw/000B57FFFED8F078/apsresponse
> 2020-12-10T02:47:41.445Z - info: MQTT Received (message): {"statusType":"apsAck","eui64":"0x000B57FFFEDE9FD1","status":"0x00","clusterId":"0x0004","commandId":"0x0E"}
> 2020-12-10T02:47:41.445Z - info: MQTT Published Topic: publishstate
> 2020-12-10T02:47:41.445Z - info: Gateway: Handling Publish State Message
> Handling Commands Message: {"commands":[{"command":"plugin network-creator-security open-network","postDelayMs":100}]}
> 2020-12-10T02:47:41.490Z - info: MQTT Published Topic: commands Payload: {"commands":[{"command":"plugin network-creator-security open-network","postDelayMs":100}]}
> 2020-12-10T02:47:41.490Z - info: MQTT Received (topic): gw/000B57FFFED8F078/publishstate
> 2020-12-10T02:47:41.490Z - info: MQTT Received (message): {}
> 2020-12-10T02:47:41.491Z - info: MQTT Received (topic): gw/000B57FFFED8F078/commands
> 2020-12-10T02:47:41.491Z - info: MQTT Received (message): {"commands":[{"command":"plugin network-creator-security open-network","postDelayMs":100}]}
> 2020-12-10T02:47:41.494Z - info: Gateway: 0E49:  
> Simple Descriptor Response
> 2020-12-10T02:47:41.495Z - info: MQTT Received (topic): gw/000B57FFFED8F078/settings
> 2020-12-10T02:47:41.495Z - info: MQTT Received (message): {"ncpStackVersion":"6.2.3-204","networkUp":true,"networkPanId":"0x2000","radioTxPower":30,"radioChannel":11}
> 2020-12-10T02:47:41.497Z - info: MQTT Received (topic): gw/000B57FFFED8F078/relays
> 2020-12-10T02:47:41.497Z - info: MQTT Received (message): {"relays":[]}
> 2020-12-10T02:47:41.497Z - info: MQTT Received (topic): gw/000B57FFFED8F078/devices

>

**Comment by cdjackson** [comment]
I'm not sure what versions of anything you are using, or really what you're trying to do here. Probably you have something misconfigured for your system.  One thing you can try is to change the `EZSP_TC_KEY_REQUEST_POLICY` to use a new key.

**Comment by trunghtdev** [comment]
Thank you!

**Comment by cdjackson** [comment]
I'm not sure that this will work in the longer term as this will not allow devices to join the network. You might want to try `EZSP_ALLOW_TC_KEY_REQUEST_AND_GENERATE_NEW_KEY` to see if that helps.

**Comment by trunghtdev** [comment]
It worked

Thank you
