### ISSUE TITLE
Branch 'master' can't be built

### ISSUE THREAD

**Issue by TomTravaglino** [zsmartsystems/com.zsmartsystems.zigbee#1250]
The latest version on master can't be built. It fails to compile `com.zsmartsystems.zigbee/com.zsmartsystems.zigbee/src/main/java/com/zsmartsystems/zigbee/zdo/command/ParentAnnounce.java` with such an error

```
[ERROR] /home/tom/Dev/git_repos/com.zsmartsystems.zigbee/com.zsmartsystems.zigbee/src/main/java/com/zsmartsystems/zigbee/zdo/command/ParentAnnounce.java:[44,18] cannot find symbol
[ERROR]   symbol:   class ParentAnnounceChildInfo
[ERROR]   location: class com.zsmartsystems.zigbee.zdo.command.ParentAnnounce
```

A look at `ParentAnnounce` reveals that it's importing `ParentAnnounceChildInfo` from the wrong package `com.zsmartsystems.zigbee.zcl.field` instead of `com.zsmartsystems.zigbee.zdo.field`. Or am I missing something?

**Comment by cdjackson** [comment]
Thanks @TomTravaglino I will take a double check at this tonight as I thought I'd compiled master only a day or two ago which seems strange given your PR, but I assume you are probably correct.
