### ISSUE TITLE
Ember no longer controlling devices after 30-50 minutes

### ISSUE THREAD

**Issue by AfromD** [zsmartsystems/com.zsmartsystems.zigbee#178]
I have reported this previously in the forum. My Ember stick (nortel) will no longer control any devices after running for less than an hour. It will still register changes on the network. The following log shows me commanding brightness on a lamp to zero at 11:13:33. In Paper UI, the brightness updates to 0, however, the lamp itself does not react. Meanwhile, you can see a motion sensor updating, which is acted upon correctly by openhab.

Properties of the zigbee thing I tried to control:

zigbee_logicaltype | ROUTER
-- | --
zigbee_powerlevel | FULL
modelId | LCT010
zigbee_networkaddress | 27819
zigbee_powersource | MAINS
zigbee_stkversion | 1
zigbee_datecode | 20160906
zigbee_zclversion | 1
zigbee_routes | []
zigbee_lastupdate |  
vendor | Philips
zigbee_appversion | 2
zigbee_permitjoining | false
zigbee_powermode | RECEIVER_ON_IDLE
zigbee_powersources | [MAINS, RECHARGABLE_BATTERY, DISPOSABLE_BATTERY]
hardwareVersion | 1
zigbee_neighbors | []
firmwareVersion | 01000B0E
zigbee_devices | []

Log when things don't work:
[New Text Document.txt](https://github.com/openhab/org.openhab.binding.zigbee/files/1628235/New.Text.Document.txt)
Next is how a functioning command turns up in the log. All the TX commands seem to missing from above posted log.
[Neues Textdokument.txt](https://github.com/openhab/org.openhab.binding.zigbee/files/1628293/Neues.Textdokument.txt)

**Comment by cdjackson** [comment]
Closing for now until this is shown to be an issue with the ember (sorry for the ping-pong issue game ;) ).
https://github.com/openhab/org.openhab.binding.zigbee/issues/86
