### ISSUE TITLE
Mesh update node changed check not working

### ISSUE THREAD

**Issue by cdjackson** [zsmartsystems/com.zsmartsystems.zigbee#184]
When the mesh update completes, it copies the new data into the node. It then does a check to see if the node has changed, and if so, it then sends the notification to listeners. Since the node is updated already, the check always fails and notifications are not sent.

The update of the node in the mesh update code should be looked at to improve this.

#183

**Comment by TheWizz** [comment]
I'm not sure I understand where in the code "it copies the new data into the node", which would then be the place to look for actual changes, I guess. I would really like to get rid of the redundant notifications and _in particular_ the re-serialization of the entire node graph whenever updateNode is called.
