### ISSUE TITLE
Frequent logging when command is not supported

### ISSUE THREAD

**Issue by openhab-5iver** [zsmartsystems/com.zsmartsystems.zigbee#223]
[openHAB forum](https://community.openhab.org/t/zigbee-binding/15763/864?u=5iver)

**Comment by cdjackson** [comment]
```
PowerDescriptorResponse [0/0 -> 0/0, cluster=8003, TID=NULL, status=NO_DESCRIPTOR, nwkAddrOfInterest=null, powerDescriptor=null]
```

**Comment by cdjackson** [comment]
From the original OH forum discussion -:

```
2018-02-19 19:15:50.060 [DEBUG] [ystems.zigbee.internal.ZigBeeNodeServiceDiscoverer] - 7CE524000014AF33: Node SVC Discovery ManagementRoutingRequest returned CommandResult [ERROR (UNKNOWN,0x02), ManagementRoutingResponse [7491/0 -> 0/0, cluster=8032, TID=NULL, status=NOT_SUPPORTED, routingTableEntries=null, startIndex=null, routingTableList=[]]]
```

**Comment by openhab-5iver** [comment]
Are you asking/stating something or making notes? 😄

**Comment by cdjackson** [comment]
Just making notes so I don’t have to find the relevant bits in the forum each time ;)

**Comment by openhab-5iver** [comment]
And I'll make a note of that for when reporting issues in the future!

**Comment by cdjackson** [comment]
Thanks - the reference to the forum is good as it gives the background, but it’s nice to have the nitty gritty in the issue :)

**Comment by cdjackson** [comment]
This should be closed. The mesh update is handling the NOT_SUPPORTED response and will not request these messages again after the first unsupported response.
