### ISSUE TITLE
Maven Clean Install failed on com.zsmartsystems.zigbee.test

### ISSUE THREAD

**Issue by ncpe20012003** [zsmartsystems/com.zsmartsystems.zigbee#272]
Using Maven 3.5.3 on Debian Stretch.
[ERROR] Failed to execute goal com.gavinmogan:codacy-maven-plugin:1.0.3:coverage (codacy-upload-coverage) on project com.zsmartsystems.zigbee.test: The parameters 'apiToken', 'projectToken' for goal com.gavinmogan:codacy-maven-plugin:1.0.3:coverage are missing or invalid

**Comment by cdjackson** [comment]
This can be ignored, but I will try and find a way to avoid the failure. The issue is just that you don’t have the API codes to upload the coverage results to codacy.com.

**Comment by cdjackson** [comment]
I've changed the phase in which this runs, so it shouldn't error on a standard build any more.
