### ISSUE TITLE
Missing content of ember autocode module

### ISSUE THREAD

**Issue by hsudbrock** [zsmartsystems/com.zsmartsystems.zigbee#344]
I stumbled upon the module `com.zsmartsystems.zigbee.dongle.ember.autocode` not containing any code, when looking for how the autogenerated classes in `com.zsmartsystems.zigbee.dongle.ember` are actually generated.

Do you already know then this code will be added to the project?

**Comment by hsudbrock** [comment]
OK, thanks for the quick info @cdjackson! I am looking forward to any future plans for adding this :)

**Comment by cdjackson** [comment]
Ok, let's see in future.
