### ISSUE TITLE
Change to Java 8

### ISSUE THREAD

**Issue by cdjackson** [zsmartsystems/com.zsmartsystems.zigbee#397]
I am considering making the minimum JDK requirement 1.8 instead of 1.7 as currently set. My main reasoning at the moment is to get the new ```java.time``` classes.

I don't think the change to Java 8 should cause problems, but I'll leave this open for comment for a while before doing anything.

FYI @Shyamranny, @hsudbrock, @cschwer - if this would cause problems, please advise.

**Comment by Shyamranny** [comment]
@cdjackson , thanks for informing. I am good. I don't have any issue with it.

**Comment by hsudbrock** [comment]
@cdjackson Thanks for the update, I don't have any issues with this step.

**Comment by cdjackson** [comment]
Closed by #408
