### ISSUE TITLE
SPI Bridge doesn't come up in v1.1.2

### ISSUE THREAD

**Issue by TomTravaglino** [zsmartsystems/com.zsmartsystems.zigbee#398]
Since we switched to version 1.1.2 on our machine with SPI the bridge doesn't come up. The status of the bridge is `Status=OFFLINE: Bad response received from dongle`. We stepped back to our previous version (1.0.15) and then it worked again. So we assume that something has changed and  makes the bridge not going ONLINE.
We also checked v1.1.2 on a machine with a Ember-dongle (UART) and it works there. It seems to be a SPI specific issue.

I attached a log file which contains the entries of the network start procedure.

[logs.txt](https://github.com/zsmartsystems/com.zsmartsystems.zigbee/files/2397305/logs.txt)

**Comment by cdjackson** [comment]
It looks like your firmware has an issue with the ```EZSP_CONFIG_BROADCAST_TABLE_SIZE``` setting. I would suggest trying a lower value.

You can adjust this with the ```updateDefaultConfiguration()``` method from within your implementation before calling ```initialize()```.

I don't think this is related to SPI, but to the version of firmware, or possibly to the available memory in the processor.

**Comment by tomhoefer** [comment]
do you think that we can really use a number lower than 15 for this parameter? the spec says that the min value for this param should be 15

**Comment by cdjackson** [comment]
I don’t know - you log shows the device complains about this value, so either try another one, or remove this configuration by setting it to null and it will be the same as the previous version.

**Comment by cdjackson** [comment]
@TomTravaglino can we close this or is there still an issue?

**Comment by TomTravaglino** [comment]
This issue is solved.

**Comment by hsudbrock** [comment]
The issue was - as far as I see - not related to the broadcast table size (although it looks weird to me that our dongles complain that the set value (which looks totally valid to me) would be invalid). The issue was caused by introducing the possibility to set an arbitrary link key, and to changing the default value handling for the radio channel, and both is resolved by using the most recent version of the binding.
