### ISSUE TITLE
Noob - how to compile?

### ISSUE THREAD

**Issue by amercer86** [zsmartsystems/com.zsmartsystems.zigbee#434]
I've never had to compile or build my own jar and frankly I'm spinning my wheels. I've tried both maven and gradle with no success. Are there any step by step instructions for compiling this? I'm so frustrated...

**Comment by cdjackson** [comment]
As per the doc, use Maven -:

To build: ```mvn clean install```

Obviously you need to clone the repository first, and install maven.

**Comment by amercer86** [comment]
I appreciate the feedback. I _did_ see those instructions - I think I was making it a lot harder than it is.

It appears to be working. Thanks again!

**Comment by cdjackson** [comment]
No problem - I'm glad you got it running.
