### ISSUE TITLE
Feature request: support StepColorTemperature command from the Color Control cluster

### ISSUE THREAD

**Issue by hsudbrock** [zsmartsystems/com.zsmartsystems.zigbee#438]
The Osram Lightify Switch emits `StepColorTemperature` commands (command ID `0x4C`) from the color control cluster (`0x0300`). This command is not supported currently by this library.

Would it be possible to add this command (and, when doing this, maybe also `0x4B MoveColorTemperature`, although this is not relevant for integrating the Osram switch)?

**Comment by hsudbrock** [comment]
If I have not missed it by accident, I think that these two commands are not included in the new XML definition of the color control cluster (cf. https://github.com/zsmartsystems/com.zsmartsystems.zigbee/pull/527).

Do you think it would be an option to add those command directly with the new autocoder?

**Comment by cdjackson** [comment]
Please feel free to provide a PR. These are not in the public standard as far as I know.

**Comment by cdjackson** [comment]
This is now included in the new autocoder and will be merged into ```1.2.0```.

**Comment by cdjackson** [comment]
Closed by #527
