### ISSUE TITLE
Framecounter stored as signed int in java, but it is an unsigned int, i.e. 0 - 2^32-1

### ISSUE THREAD

**Issue by triller-telekom** [zsmartsystems/com.zsmartsystems.zigbee#508]
I have a question regarding the storage of the incoming and outgoing frame counter of zigbeekeys.

Here it is stored as an `Integer`: https://github.com/zsmartsystems/com.zsmartsystems.zigbee/blob/master/com.zsmartsystems.zigbee/src/main/java/com/zsmartsystems/zigbee/security/ZigBeeKey.java#L23

Since this is java code, the integer is signed and thus -2^31 -> 2^31

But I thought that the counter is defined as a unsigned integer, counting only positive values from 0 to 2^32-1.

So my question is, if we only count until half of it. I.e. what happens if the counter inside the firmware of a device is > 2^31-1? Will it be stored as a negative number in the java code because the integer overflows?

**Comment by cdjackson** [comment]
> The only comparison that one might face is when he wants to try to "increase" the framecounter after restoring a backup containing the old one.

There is no need to increase it so much. My implementation for increasing it is to assume 1 frame per second was transmitted, so unless you are waiting many years (eg 30!), you will never get so high.

;)
