### ISSUE TITLE
Disable join not working properly

### ISSUE THREAD

**Issue by milansamardzic** [zsmartsystems/com.zsmartsystems.zigbee#532]
Disable join not working properly. 

Found and fix the issue. I will create a pull request. 
This ticket is only for tracking status.

Here is PR:
[https://github.com/zsmartsystems/com.zsmartsystems.zigbee/pull/533](url)

**Comment by cdjackson** [comment]
Please can you describe the problem that you don't really provide any explanation about what doesn't work?

**Comment by cdjackson** [comment]
> Disable join not working properly.

Please can you advise your problem, and your system information as there is currently no known issue here - at least with Telegesis and Ember dongles.

**Comment by cdjackson** [comment]
@milansamardzic do you have any further information or shall we close this?

**Comment by cdjackson** [comment]
This has been open for 2 months with no feedback, so I'm closing this for now. If you have further information, please post it and we can discuss again!
