### ISSUE TITLE
Reduce keep-alive polling in Ember dongle

### ISSUE THREAD

**Issue by cdjackson** [zsmartsystems/com.zsmartsystems.zigbee#538]
Currently there is polling in the Ember dongle that polls every second in order to check if the NCP is still alive. On large systems, this accounts for a considerable load and we should look at reducing this to improve efficiency.

@triller-telekom what do you think? Either we don't poll when there are frames in the queue, or we don't poll if frames have been passed through the dongle layer within x period?

**Comment by triller-telekom** [comment]
> Either we don't poll when there are frames in the queue

Sounds plausible and we should do that.

> we don't poll if frames have been passed through the dongle layer within x period

Hmm, I am not entirely sure what is the best solution here. But at a first glance I would say that maybe we should just increase the polling period to 2 or 3 seconds. Int hat way it will take longer until the device goes offline, but should still be sufficient.

**Comment by cdjackson** [comment]
In order to keep the noise down, in the Telegesis implementation it checks to see if there are messages queued, and if so, it doesn't send the poll as it is just overhead.

I know that the Telegesis is implemented a little differently in that the polling is done in the lower layer handler, but I think that doing something similar is best to remove any unnecessary noise.

When we added this to Telegesis, Thomas would not accept a value above 1 second....
