### ISSUE TITLE
Nodes cli command issues getting basic information

### ISSUE THREAD

**Issue by cdjackson** [zsmartsystems/com.zsmartsystems.zigbee#553]
Following #541 if there are issues getting the basic information, then the nodes cli command gets spread over a long duration making it difficult to use now when we just want to see the list of nodes. I would suggest that the BASIC information that was added in this change should not be requested by default, and we should have an option to request it.

This could be implemented with a Long.MAX_VALUE as the refresh time to allow the information to be displayed if it is already known, but not requested if it isn't.

@hsudbrock WDYT?

**Comment by hsudbrock** [comment]
Hm, I think you are right, this is a drawback of my changes that does not really stand out when using the openHAB binding (as this always requests these values at discovery time).

I agree with your suggestion for improvement (let me create a PR later for adding this).

**Comment by hsudbrock** [comment]
> This could be implemented with a Long.MAX_VALUE as the refresh time to allow the information to be displayed if it is already known, but not requested if it isn't.

This is actually already implemented like this; it does not help though, because even with a refresh time of `Long.MAX_VALUE` the attribute value is requested from the device if the value is not already known.

I will use a flag for the command to improve the situation.
