### ISSUE TITLE
Bug when generating attributes initialization in autocoder (1.2.0) 

### ISSUE THREAD

**Issue by TomTravaglino** [zsmartsystems/com.zsmartsystems.zigbee#613]
In the method `ZigBeeZclClusterGenerator.createInitializeAttributes(...)` there is a if-statement which prevents client attributes from being processed. As consequence the generated map is always empty.

This is the statement which very likely needs to be removed
```
                if (!attribute.side.equalsIgnoreCase("server")) {
                    continue;
                }
```

**Comment by cdjackson** [comment]
This is now updated
