### ISSUE TITLE
v1.2.0: Missing method 'readAttributeValue' in cluster class(es)

### ISSUE THREAD

**Issue by TomTravaglino** [zsmartsystems/com.zsmartsystems.zigbee#614]
In #591 the specific attribute methods of the cluster classes have been marked as deprecated (in v1.2.0). Some javadocs now advise to use `readAttributeValue(ZclAttribute, Long)` instead. But this method doesn't seem to exist. Is the method missing or is the javadoc wrong?

**Comment by cdjackson** [comment]
Javadoc is incorrect - I'll update it.
