### ISSUE TITLE
Next release date?

### ISSUE THREAD

**Issue by wsowa** [zsmartsystems/com.zsmartsystems.zigbee#650]
More a question than an issue. Do you have a next release scheduled already? If so then when. 
I'm interested in seeing some of not yet released code in the openHAB zigbee plugin...

**Comment by cdjackson** [comment]
This should be in the coming week or two - the OH updates are being managed as well, and I'm just finalising changes in 1.2 and possible deprecation of the TI dongle (although this might wait for the next revision).
