### ISSUE TITLE
Group Support is partial

### ISSUE THREAD

**Issue by tunjid** [zsmartsystems/com.zsmartsystems.zigbee#684]
**Is your feature request related to a problem? Please describe.**

Group support:

1. While I can create a group with the `GroupAddCommand` and add nodes to the group with the `MembershipAddCommand` and get a success response, querying the node for the groups it's a part of with `MembershipListCommand` returns no groups. The same goes for the `MembershipViewCommand` which completes successfully, but returns an empty String for the group's name.

2. Commands like On, Off, Level and Color only support `ZigBeeEndpointAddress`, and not `ZigBeeGroupAddress`

**Describe the solution you'd like**

1. That nodes added to a group return the groups they are a part of when queried.

2. That commands support all instances of `ZigBeeAddress`.

**Describe alternatives you've considered**
I'd absolutely love to contribute and submit a pull request, I'd just like some pointers on where to start. I'm using the TI CC2531 dongle.

**Comment by cdjackson** [comment]
Group support has been added as of 1.3.11. It may only work fully for Ember chipsets but full support for group and scene clusters has been added.
