### ISSUE TITLE
Telegesis dongle: Transaction retry counter not reset

### ISSUE THREAD

**Issue by yoadey** [zsmartsystems/com.zsmartsystems.zigbee#737]
**Describe the bug**
In TelegesisFrameHandler exists a retry counter for failed transactions. After a successful transaction it should be reset to zero, but currently the reset is not implemented. This leads to a stop of the communication with the dongle if there occur 3 timeouts in total and not just directly after each other.
In log, the message `TELEGESIS Timer: Timeout #` counts up to 3 while many other commands have been successful send.

**To Reproduce**
1. Start zigbee with a telegesis dongle
2. Send many commands, even if they have not been fully processed yet

**Expected behavior**
All commands are processed or dropped, communication with the dongle stays alive.

**Additional context**
Is in context with https://github.com/openhab/org.openhab.binding.zigbee/issues/474, but does not fully solve this issue.

Will soon add a pull request for this

**Comment by cdjackson** [comment]
Closed by #738
