### ISSUE TITLE
Serial: xon/xoff flow control is only set in one direction

### ISSUE THREAD

**Issue by sesuncedu** [zsmartsystems/com.zsmartsystems.zigbee#774]
I see ASH NAK frames in, but not out. They seem to usually occur during discovery bursts. 

stty -a on the dongle shows ```ixon -ixoff```

I can't remember which direction is which so I don't know if this is in the slightest bit relevant. I will try changing the settings from the shell and see what breaks. 

Cf

https://github.com/zsmartsystems/com.zsmartsystems.zigbee/blob/253741954f36dcd3eb438a365e0083328f26e812/com.zsmartsystems.zigbee.serial/src/main/java/com/zsmartsystems/zigbee/serial/ZigBeeSerialPort.java#L144

with

https://github.com/zsmartsystems/com.zsmartsystems.zigbee/blob/253741954f36dcd3eb438a365e0083328f26e812/com.zsmartsystems.zigbee.serial/src/main/java/com/zsmartsystems/zigbee/serial/ZigBeeSerialPort.java#L141

**Comment by cdjackson** [comment]
Please feel free to provide a PR if you want to resolve this. Clearly this is not part of the framework so doesn't really matter for implementations.
