### ISSUE TITLE
Ember: Can ASH windowing be enabled? 

### ISSUE THREAD

**Issue by sesuncedu** [zsmartsystems/com.zsmartsystems.zigbee#775]
TX_WINDOW (TX_K) is set to 1, but there seems to be infrastructure in place that looks intended to support larger windows.

Is this code known good / known bad for 1 < TK < 8?

**Comment by cdjackson** [comment]
Please feel free to test and provide any PRs required.

**Comment by sesuncedu** [comment]
Thanks for update - I wanted to check if the state was known first.

**Comment by cdjackson** [comment]
I’m not sure if I’ve tested this or not - it was written a few years back now and there’s never really been a need to change the windowing.

**Comment by cdjackson** [comment]
@sesuncedu can we close this question?
