### ISSUE TITLE
Question: Origin of ZCL XML files

### ISSUE THREAD

**Issue by TheBlubb14** [zsmartsystems/com.zsmartsystems.zigbee#843]
Where did you get the ZCL XML files from, or how did you generate them?

**Comment by cdjackson** [comment]
I created them myself.

**Comment by TheBlubb14** [comment]
What documents did you create them from?

**Comment by cdjackson** [comment]
The ZigBee protocol definition documents as defined by ZigBee.

**Comment by TheBlubb14** [comment]
Ok, thanks
